### ISSUE TITLE
traceback.format_exception fails on Python >= 3.10

### ISSUE THREAD

**Issue by brunoloureiro** [radhelper/radiation-setup#2]
The call to traceback.format_exception in server.py#34 fails on Python version >= 3.10.

Cause: Function signature changed ([https://docs.python.org/3/library/traceback.html#traceback.format_exception](https://docs.python.org/3/library/traceback.html#traceback.format_exception)).

Solution: Update the function call to match the new signature.

The code below (should) work on most versions:

```
    if sys.version_info.major >= 3 and sys.version_info.minor >= 10:
        exception_str = "".join(
            traceback.format_exception(args.exc_value)
        )
    else:
        exception_str = "".join(
            traceback.format_exception(etype=args.exc_type, value=args.exc_value, tb=args.exc_traceback)
        )
```

edit: (args) -> (args.exc_value)

**Comment by fernandoFernandeSantos** [comment]
This should be fixed now. Additionally, the server now runs only with Python >=3.10
